[webserver]
port = 9595

[logging]
level = 5 #Debug

[database]
username = "root"
password = "muni123chavva"
dbname = "shoppinglist"
ip = "mysql"
port = 3306
max_connection_attempt = 60

[kv]
ip = "redis"